package runtime

import (
	"encoding/json"
	"errors"
	"strconv"
	"strings"
)

const (
	maxSessions       = 64
	maxReplayRequests = 128
	maxRequestIDBytes = 256
	maxTextBytes      = 256 << 10
	maxHistoryEvents  = 256
	maxHistoryBytes   = 2 << 20
	maxOutboundBytes  = 8 << 20
)

var ErrEventHistoryExpired = errors.New("event history expired")

// issuedSession recognizes only canonical IDs generated by this engine. Deleted
// sessions can remain closed/idempotent without accumulating tombstones.
func (e *Engine) issuedSession(id string) bool {
	suffix, ok := strings.CutPrefix(id, "session-")
	if !ok {
		return false
	}
	n, err := strconv.ParseUint(suffix, 10, 64)
	return err == nil && n > 0 && n <= e.nextSession && strconv.FormatUint(n, 10) == suffix
}

// releaseSession must run under e.mu, and only after any provider has returned.
func (e *Engine) releaseSession(id string) {
	delete(e.sessions, id)
	delete(e.events, id)
}

func remember(s *engineSession, key string, response Message) {
	// RPC IDs belong to the current transport call, not the cached side effect.
	response.ID = nil
	response.Result = append(json.RawMessage(nil), response.Result...)
	s.requests[key] = response
}

// EventsSince returns the retained events after seq. An expired cursor is an
// explicit error; this diagnostic history is not durable protocol replay.
func (e *Engine) EventsSince(sessionID string, seq uint64) ([]Message, error) {
	e.mu.Lock()
	defer e.mu.Unlock()
	s, ok := e.sessions[sessionID]
	if !ok || seq < s.historyFloor {
		return nil, ErrEventHistoryExpired
	}
	var result []Message
	for _, event := range e.events[sessionID] {
		var fields struct {
			Seq uint64 `json:"event_seq"`
		}
		_ = json.Unmarshal(event.Params, &fields)
		if fields.Seq > seq {
			event.Params = append(json.RawMessage(nil), event.Params...)
			result = append(result, event)
		}
	}
	return result, nil
}
