package runtime

import (
	"encoding/json"
	"errors"
	"strconv"
	"strings"
)

const (
	maxSessions       = 64
	maxReplayRequests = 128
	maxRequestIDBytes = 256
	maxTextBytes      = 256 << 10
	maxHistoryEvents  = 256
	maxHistoryBytes   = 2 << 20
	maxOutboundBytes  = 8 << 20
	// maxEngineHistoryBytes bounds the sum the per-session caps would otherwise
	// multiply: maxSessions * maxHistoryBytes is 128 MiB per connection, and
	// maxConnections of those 4 GiB of retained history a peer can pin.
	maxEngineHistoryBytes = 16 << 20
)

var (
	ErrEventHistoryExpired = errors.New("event history expired")
	// errDeliveryRefused reports transport backpressure. The events stay retained,
	// so the client recovers by resuming again once it has drained.
	errDeliveryRefused = errors.New("event delivery refused; resume again after draining")
)

// issuedSession recognizes only canonical IDs generated by this engine. Deleted
// sessions can remain closed/idempotent without accumulating tombstones.
func (e *Engine) issuedSession(id string) bool {
	suffix, ok := strings.CutPrefix(id, "session-")
	if !ok {
		return false
	}
	n, err := strconv.ParseUint(suffix, 10, 64)
	return err == nil && n > 0 && n <= e.nextSession && strconv.FormatUint(n, 10) == suffix
}

// releaseSession must run under e.mu, and only after any provider has returned.
// Returning the session's share of the engine budget is what keeps a long
// connection that opens and closes sessions from exhausting it.
func (e *Engine) releaseSession(id string) {
	if s, ok := e.sessions[id]; ok {
		e.historyBytes -= s.historyBytes
		s.historyBytes = 0
	}
	delete(e.sessions, id)
	delete(e.events, id)
}

// evictLargest frees engine budget by dropping the oldest event of whichever
// session retains the most, so one busy session cannot starve the others out of
// their history. It reports whether anything was reclaimed. Runs with e.mu held.
func (e *Engine) evictLargest() bool {
	var victim string
	var chosen *engineSession
	for id, s := range e.sessions {
		if len(e.events[id]) == 0 {
			continue
		}
		if chosen == nil || s.historyBytes > chosen.historyBytes {
			victim, chosen = id, s
		}
	}
	if chosen == nil {
		return false
	}
	e.evictOldest(victim, chosen)
	return true
}

// evictOldest drops the oldest retained event of one session, advancing its
// history floor so an expired cursor is reported rather than silently skipped.
// It must run with e.mu held.
func (e *Engine) evictOldest(id string, s *engineSession) {
	history := e.events[id]
	if len(history) == 0 {
		return
	}
	size := len(history[0].Params)
	s.historyBytes -= size
	e.historyBytes -= size
	s.historyFloor++
	history[0] = Message{}
	e.events[id] = history[1:]
}

func remember(s *engineSession, key string, response Message) {
	// RPC IDs belong to the current transport call, not the cached side effect.
	response.ID = nil
	response.Result = append(json.RawMessage(nil), response.Result...)
	s.requests[key] = response
}

// EventsSince returns the retained events after seq. An expired cursor is an
// explicit error; this diagnostic history is not durable protocol replay.
func (e *Engine) EventsSince(sessionID string, seq uint64) ([]Message, error) {
	e.mu.Lock()
	defer e.mu.Unlock()
	s, ok := e.sessions[sessionID]
	if !ok || seq < s.historyFloor {
		return nil, ErrEventHistoryExpired
	}
	var result []Message
	for _, event := range e.events[sessionID] {
		var fields struct {
			Seq uint64 `json:"event_seq"`
		}
		_ = json.Unmarshal(event.Params, &fields)
		if fields.Seq > seq {
			event.Params = append(json.RawMessage(nil), event.Params...)
			result = append(result, event)
		}
	}
	return result, nil
}
